name: train_val_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=20.3.3
  - requests=2.24.0
  - scikit-learn=0.24.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - git+https://github.com/Batmabraham/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
